<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Análisis exploratorio de datos | Notas de Métodos Estadísticos</title>
  <meta name="description" content="Notas de clase y ejercicios del curso de Métodos Estadísticos" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Análisis exploratorio de datos | Notas de Métodos Estadísticos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notas de clase y ejercicios del curso de Métodos Estadísticos" />
  <meta name="github-repo" content="josevang0811/Analisis_exploratorio" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Análisis exploratorio de datos | Notas de Métodos Estadísticos" />
  
  <meta name="twitter:description" content="Notas de clase y ejercicios del curso de Métodos Estadísticos" />
  

<meta name="author" content="Jose Fernando Van Strahlen y Jairo Hernandez" />


<meta name="date" content="2026-08-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="estadística-paramétrica-y-no-paramétrica.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de Métodos Estadísticos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#datos-y-paquetes"><i class="fa fa-check"></i>Datos y paquetes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Análisis exploratorio de datos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#analisis-exploratorio-de-median_house_value"><i class="fa fa-check"></i><b>1.1</b> Analisis exploratorio de median_house_value</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#analisis-de-las-variables-independientes-caracteristicas"><i class="fa fa-check"></i><b>1.2</b> Analisis de las variables independientes (Caracteristicas)</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#ejercicio-1.-gr%C3%A1ficas-e-interpretaci%C3%B3n-de-las-variables-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>1.2.1</b> Ejercicio 1. Gráficas e interpretación de las variables características</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#analisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>1.3</b> Analisis exploratorio bivariado</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#ejercicio-2.-diagramas-de-dispersi%C3%B3n-con-las-dem%C3%A1s-variables"><i class="fa fa-check"></i><b>1.3.1</b> Ejercicio 2. Diagramas de dispersión con las demás variables</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#ejercicio-3.-errores-del-gr%C3%A1fico-de-ggpairs"><i class="fa fa-check"></i><b>1.3.2</b> Ejercicio 3. Errores del gráfico de <code>ggpairs</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html"><i class="fa fa-check"></i><b>2</b> Estadística paramétrica y no paramétrica</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#presi%C3%B3n-sist%C3%B3lica-contra-diast%C3%B3lica-independientes-param%C3%A9trica"><i class="fa fa-check"></i><b>2.1</b> Presión sistólica contra diastólica (independientes, paramétrica)</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-4.-an%C3%A1lisis-exploratorio-de-los-datos-de-presi%C3%B3n"><i class="fa fa-check"></i><b>2.1.1</b> Ejercicio 4. Análisis exploratorio de los datos de presión</a></li>
<li class="chapter" data-level="2.1.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuesto-de-normalidad"><i class="fa fa-check"></i><b>2.1.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.1.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-5.-verificaci%C3%B3n-de-var.test-con-el-teorema-de-raz%C3%B3n-de-varianzas"><i class="fa fa-check"></i><b>2.1.3</b> Ejercicio 5. Verificación de <code>var.test</code> con el teorema de razón de varianzas</a></li>
<li class="chapter" data-level="2.1.4" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-6.-teorema-de-la-diferencia-de-medias"><i class="fa fa-check"></i><b>2.1.4</b> Ejercicio 6. Teorema de la diferencia de medias</a></li>
<li class="chapter" data-level="2.1.5" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>2.1.5</b> Tamaño del efecto</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#precios-por-tipo-de-cuenta-con-varianzas-distintas"><i class="fa fa-check"></i><b>2.2</b> Precios por tipo de cuenta, con varianzas distintas</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-7.-an%C3%A1lisis-exploratorio-de-los-precios"><i class="fa fa-check"></i><b>2.2.1</b> Ejercicio 7. Análisis exploratorio de los precios</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuesto-de-normalidad-1"><i class="fa fa-check"></i><b>2.2.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-8.-bartlett-levene-y-fligner-killeen"><i class="fa fa-check"></i><b>2.2.3</b> Ejercicio 8. Bartlett, Levene y Fligner-Killeen</a></li>
<li class="chapter" data-level="2.2.4" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#prueba-t-con-la-correcci%C3%B3n-de-welch"><i class="fa fa-check"></i><b>2.2.4</b> Prueba t con la corrección de Welch</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#dos-grupos-pareados-param%C3%A9trica"><i class="fa fa-check"></i><b>2.3</b> Dos grupos pareados, paramétrica</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-9.-an%C3%A1lisis-exploratorio-de-los-tiempos"><i class="fa fa-check"></i><b>2.3.1</b> Ejercicio 9. Análisis exploratorio de los tiempos</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuesto-de-normalidad-2"><i class="fa fa-check"></i><b>2.3.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.3.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-10.-teorema-de-la-diferencia-de-medias-para-datos-pareados"><i class="fa fa-check"></i><b>2.3.3</b> Ejercicio 10. Teorema de la diferencia de medias para datos pareados</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#dos-grupos-independientes-no-param%C3%A9trica"><i class="fa fa-check"></i><b>2.4</b> Dos grupos independientes, no paramétrica</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-11.-an%C3%A1lisis-exploratorio-del-peso-al-nacer"><i class="fa fa-check"></i><b>2.4.1</b> Ejercicio 11. Análisis exploratorio del peso al nacer</a></li>
<li class="chapter" data-level="2.4.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuesto-de-normalidad-3"><i class="fa fa-check"></i><b>2.4.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.4.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#homogeneidad-de-varianzas"><i class="fa fa-check"></i><b>2.4.3</b> Homogeneidad de varianzas</a></li>
<li class="chapter" data-level="2.4.4" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#prueba-de-mann-whitney"><i class="fa fa-check"></i><b>2.4.4</b> Prueba de Mann-Whitney</a></li>
<li class="chapter" data-level="2.4.5" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-12.-se-puede-usar-una-prueba-param%C3%A9trica"><i class="fa fa-check"></i><b>2.4.5</b> Ejercicio 12. ¿Se puede usar una prueba paramétrica?</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#dos-grupos-pareados-no-param%C3%A9trica"><i class="fa fa-check"></i><b>2.5</b> Dos grupos pareados, no paramétrica</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#ejercicio-13.-an%C3%A1lisis-exploratorio-del-cuestionario"><i class="fa fa-check"></i><b>2.5.1</b> Ejercicio 13. Análisis exploratorio del cuestionario</a></li>
<li class="chapter" data-level="2.5.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuesto-de-normalidad-4"><i class="fa fa-check"></i><b>2.5.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.5.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#prueba-de-rangos-con-signo-de-wilcoxon"><i class="fa fa-check"></i><b>2.5.3</b> Prueba de rangos con signo de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#anova"><i class="fa fa-check"></i><b>2.6</b> ANOVA</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#supuestos"><i class="fa fa-check"></i><b>2.6.1</b> Supuestos</a></li>
<li class="chapter" data-level="2.6.2" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#c%C3%A1lculo-manual"><i class="fa fa-check"></i><b>2.6.2</b> Cálculo manual</a></li>
<li class="chapter" data-level="2.6.3" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#verificaci%C3%B3n-con-aov"><i class="fa fa-check"></i><b>2.6.3</b> Verificación con <code>aov</code></a></li>
<li class="chapter" data-level="2.6.4" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#comparaciones-m%C3%BAltiples"><i class="fa fa-check"></i><b>2.6.4</b> Comparaciones múltiples</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#kruskal-wallis"><i class="fa fa-check"></i><b>2.7</b> Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="estadística-paramétrica-y-no-paramétrica.html"><a href="estadística-paramétrica-y-no-paramétrica.html#comparaciones-post-hoc"><i class="fa fa-check"></i><b>2.7.1</b> Comparaciones post-hoc</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html"><i class="fa fa-check"></i><b>3</b> Guía para el parcial</a>
<ul>
<li class="chapter" data-level="3.1" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#c%C3%B3mo-se-decide-qu%C3%A9-prueba-usar"><i class="fa fa-check"></i><b>3.1</b> Cómo se decide qué prueba usar</a></li>
<li class="chapter" data-level="3.2" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#c%C3%B3mo-se-lee-cada-salida"><i class="fa fa-check"></i><b>3.2</b> Cómo se lee cada salida</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>3.2.1</b> Pruebas de normalidad</a></li>
<li class="chapter" data-level="3.2.2" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#var.test"><i class="fa fa-check"></i><b>3.2.2</b> <code>var.test</code></a></li>
<li class="chapter" data-level="3.2.3" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#t.test"><i class="fa fa-check"></i><b>3.2.3</b> <code>t.test</code></a></li>
<li class="chapter" data-level="3.2.4" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#cohen.d-y-wilcox_effsize"><i class="fa fa-check"></i><b>3.2.4</b> <code>cohen.d</code> y <code>wilcox_effsize</code></a></li>
<li class="chapter" data-level="3.2.5" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#aov-y-tukeyhsd"><i class="fa fa-check"></i><b>3.2.5</b> <code>aov</code> y <code>TukeyHSD</code></a></li>
<li class="chapter" data-level="3.2.6" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#kruskal.test-y-dunn_test"><i class="fa fa-check"></i><b>3.2.6</b> <code>kruskal.test</code> y <code>dunn_test</code></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#c%C3%B3mo-se-redacta-la-conclusi%C3%B3n"><i class="fa fa-check"></i><b>3.3</b> Cómo se redacta la conclusión</a></li>
<li class="chapter" data-level="3.4" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#errores-que-cuestan-puntos"><i class="fa fa-check"></i><b>3.4</b> Errores que cuestan puntos</a></li>
<li class="chapter" data-level="3.5" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#f%C3%B3rmulas-para-tener-a-mano"><i class="fa fa-check"></i><b>3.5</b> Fórmulas para tener a mano</a></li>
<li class="chapter" data-level="3.6" data-path="guía-para-el-parcial.html"><a href="guía-para-el-parcial.html#comandos-de-rescate-en-r"><i class="fa fa-check"></i><b>3.6</b> Comandos de rescate en R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de Métodos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Análisis exploratorio de datos<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Corresponde a la sección 3 del libro del profesor. Los datos son los precios de vivienda
del estado de California y la variable respuesta es <code>median_house_value</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="intro.html#cb2-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="intro.html#cb2-2" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span>
<span id="cb2-3"><a href="intro.html#cb2-3" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb2-4"><a href="intro.html#cb2-4" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb2-5"><a href="intro.html#cb2-5" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Datos/housing.csv&quot;</span>)</span></code></pre></div>
<p>Muestrame las 5 primeras filas</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="intro.html#cb4-1" tabindex="-1"></a><span class="fu">head</span>(data, <span class="at">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   longitude latitude housing_median_age total_rooms total_bedrooms population
## 1   -122.23    37.88                 41         880            129        322
## 2   -122.22    37.86                 21        7099           1106       2401
## 3   -122.24    37.85                 52        1467            190        496
## 4   -122.25    37.85                 52        1274            235        558
## 5   -122.25    37.85                 52        1627            280        565
##   households median_income median_house_value ocean_proximity
## 1        126        8.3252             452600        NEAR BAY
## 2       1138        8.3014             358500        NEAR BAY
## 3        177        7.2574             352100        NEAR BAY
## 4        219        5.6431             341300        NEAR BAY
## 5        259        3.8462             342200        NEAR BAY</code></pre>
<p>las estructura de los datos</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="intro.html#cb6-1" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20640 obs. of  10 variables:
##  $ longitude         : num  -122 -122 -122 -122 -122 ...
##  $ latitude          : num  37.9 37.9 37.9 37.9 37.9 ...
##  $ housing_median_age: num  41 21 52 52 52 52 52 52 42 52 ...
##  $ total_rooms       : num  880 7099 1467 1274 1627 ...
##  $ total_bedrooms    : num  129 1106 190 235 280 ...
##  $ population        : num  322 2401 496 558 565 ...
##  $ households        : num  126 1138 177 219 259 ...
##  $ median_income     : num  8.33 8.3 7.26 5.64 3.85 ...
##  $ median_house_value: num  452600 358500 352100 341300 342200 ...
##  $ ocean_proximity   : chr  &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; ...</code></pre>
<p>Datos faltantes</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="intro.html#cb8-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="intro.html#cb8-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_.{col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_.longitude NA_.latitude NA_.housing_median_age NA_.total_rooms
## 1             0            0                      0               0
##   NA_.total_bedrooms NA_.population NA_.households NA_.median_income
## 1                207              0              0                 0
##   NA_.median_house_value NA_.ocean_proximity
## 1                      0                   0</code></pre>
<p>Otra forma de detectar valores faltantes</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="intro.html#cb10-1" tabindex="-1"></a><span class="fu">missmap</span>(data)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/otra%20forma-1.png" width="672" /></p>
<p>Los 207 faltantes están todos en <code>total_bedrooms</code>, que es el 1% de los registros. Como es
una proporción pequeña y la variable es numérica, imputar por la media no mueve casi nada
la distribución.</p>
<p>Ahora, hagamos la imputacion de datos faltantes</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="intro.html#cb11-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="intro.html#cb11-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb11-3"><a href="intro.html#cb11-3" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric),</span>
<span id="cb11-4"><a href="intro.html#cb11-4" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.), <span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), .)</span>
<span id="cb11-5"><a href="intro.html#cb11-5" tabindex="-1"></a>  )) <span class="ot">-&gt;</span> df</span></code></pre></div>
<p>verifiquemos si tiene datos faltantes</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="intro.html#cb12-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="intro.html#cb12-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_.{col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_.longitude NA_.latitude NA_.housing_median_age NA_.total_rooms
## 1             0            0                      0               0
##   NA_.total_bedrooms NA_.population NA_.households NA_.median_income
## 1                  0              0              0                 0
##   NA_.median_house_value NA_.ocean_proximity
## 1                      0                   0</code></pre>
<p>vamos a convertir la variable <code>ocean_proximity</code></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="intro.html#cb14-1" tabindex="-1"></a>df<span class="sc">$</span>ocean_proximity <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>ocean_proximity)</span></code></pre></div>
<div id="analisis-exploratorio-de-median_house_value" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Analisis exploratorio de median_house_value<a href="intro.html#analisis-exploratorio-de-median_house_value" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>(Target)</p>
<p>Realicemos el resumen estadistico de la variable</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro.html#cb15-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(median_house_value),</span>
<span id="cb15-2"><a href="intro.html#cb15-2" tabindex="-1"></a>                 <span class="at">media =</span> <span class="fu">mean</span>(median_house_value),</span>
<span id="cb15-3"><a href="intro.html#cb15-3" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(median_house_value),</span>
<span id="cb15-4"><a href="intro.html#cb15-4" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(median_house_value),</span>
<span id="cb15-5"><a href="intro.html#cb15-5" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(median_house_value),</span>
<span id="cb15-6"><a href="intro.html#cb15-6" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(median_house_value, <span class="fl">0.25</span>),</span>
<span id="cb15-7"><a href="intro.html#cb15-7" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(median_house_value, <span class="fl">0.75</span>),</span>
<span id="cb15-8"><a href="intro.html#cb15-8" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(median_house_value),</span>
<span id="cb15-9"><a href="intro.html#cb15-9" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(median_house_value),</span>
<span id="cb15-10"><a href="intro.html#cb15-10" tabindex="-1"></a>                 <span class="at">asimetria =</span> <span class="fu">skewness</span>(median_house_value),</span>
<span id="cb15-11"><a href="intro.html#cb15-11" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(median_house_value))</span></code></pre></div>
<pre><code>##       n    media       sd mediana    RIC     Q1     Q3 minimo maximo asimetria
## 1 20640 206855.8 115395.6  179700 145125 119600 264725  14999 500001 0.9776922
##   curtosis
## 1   3.3275</code></pre>
<p>Centro de la distribución</p>
<p>La media es 206.855 y la mediana es 179.700. El dato clave aquí es que la media es
bastante mayor que la mediana. Cuando eso pasa, significa que hay casas muy caras,
mientras que la mitad de las casas valen 179.700 o menos.</p>
<p>Dispersión (qué tan regados están los datos)</p>
<p>La desviación estándar es 115.395, muy grande respecto a la media, los precios están muy
dispersos, no concentrados. El RIC (rango intercuartílico, Q3−Q1) es 145.125. El 50%
central de las casas cae entre Q1 = 119.600 y Q3 = 264.725.</p>
<p>Extremos</p>
<p>Mínimo 14.999 y máximo 500.001</p>
<p>Forma de la distribución</p>
<p>Asimetría = 0.98. Es positiva (sesgo a la derecha). Un valor cercano a 1 indica un sesgo
moderado-alto. Esto es coherente con lo que veías en media &gt; mediana. Curtosis = 3.33.
Como el valor de referencia de una distribución normal es 3, la distribución está apenas
por encima. Es ligeramente leptocúrtica</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="intro.html#cb17-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="intro.html#cb17-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb17-4"><a href="intro.html#cb17-4" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">25000</span>,</span>
<span id="cb17-5"><a href="intro.html#cb17-5" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>,</span>
<span id="cb17-6"><a href="intro.html#cb17-6" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb17-7"><a href="intro.html#cb17-7" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="intro.html#cb17-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb17-9"><a href="intro.html#cb17-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribucion del valor medio de las viviendas&quot;</span>,</span>
<span id="cb17-10"><a href="intro.html#cb17-10" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Valor medio de la casa (USD)&quot;</span>,</span>
<span id="cb17-11"><a href="intro.html#cb17-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-12"><a href="intro.html#cb17-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/histhousevalue-1.png" width="672" /></p>
<p>La distribución presenta un sesgo positivo (a la derecha): la mayor concentración de
viviendas se ubica en valores bajos-medios, con una cola que se extiende hacia precios
altos. Se observa además una acumulación anómala en el extremo derecho, atribuible al
truncamiento de los datos en 500.000.</p>
<p>Los mercados inmobiliarios casi siempre son sesgados a la derecha: la mayoría de viviendas
se concentra en un rango asequible-medio y una minoría de propiedades de lujo forma la
cola. Que tu distribución empírica coincida con lo que la teoría económica predice es un
buen cierre: los datos son consistentes con la realidad del fenómeno.</p>
<p>Sobre el truncamiento, vale la pena ponerle número:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="intro.html#cb18-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="intro.html#cb18-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">topes =</span> <span class="fu">sum</span>(median_house_value <span class="sc">&gt;=</span> <span class="dv">500001</span>),</span>
<span id="cb18-3"><a href="intro.html#cb18-3" tabindex="-1"></a>            <span class="at">total =</span> <span class="fu">n</span>(),</span>
<span id="cb18-4"><a href="intro.html#cb18-4" tabindex="-1"></a>            <span class="at">porcentaje =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> topes <span class="sc">/</span> total, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##   topes total porcentaje
## 1   965 20640       4.68</code></pre>
<p>Son 965 barrios, el 4,67% de la muestra, todos pegados en el mismo valor. Ese pico no es
un comportamiento del mercado sino una limitación de cómo se recogieron los datos: a todo
lo que valía más de medio millón le pusieron 500.001.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="intro.html#cb20-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="intro.html#cb20-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="intro.html#cb20-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb20-4"><a href="intro.html#cb20-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="intro.html#cb20-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb20-6"><a href="intro.html#cb20-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="intro.html#cb20-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valor medio de la casa (USD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="intro.html#cb20-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/boxhousevalue-1.png" width="672" /></p>
<p>El punto rosado es la media y está por encima de la línea de la mediana, que es la misma
señal del sesgo a la derecha vista de otra forma.</p>
</div>
<div id="analisis-de-las-variables-independientes-caracteristicas" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Analisis de las variables independientes (Caracteristicas)<a href="intro.html#analisis-de-las-variables-independientes-caracteristicas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro.html#cb21-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="intro.html#cb21-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>median_house_value) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="intro.html#cb21-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb21-4"><a href="intro.html#cb21-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb21-5"><a href="intro.html#cb21-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb21-6"><a href="intro.html#cb21-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb21-7"><a href="intro.html#cb21-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-8"><a href="intro.html#cb21-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="intro.html#cb21-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(valor),</span>
<span id="cb21-10"><a href="intro.html#cb21-10" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(valor),</span>
<span id="cb21-11"><a href="intro.html#cb21-11" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(valor),</span>
<span id="cb21-12"><a href="intro.html#cb21-12" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(valor),</span>
<span id="cb21-13"><a href="intro.html#cb21-13" tabindex="-1"></a>            <span class="at">RIC =</span> <span class="fu">IQR</span>(valor),</span>
<span id="cb21-14"><a href="intro.html#cb21-14" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.25</span>),</span>
<span id="cb21-15"><a href="intro.html#cb21-15" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.75</span>),</span>
<span id="cb21-16"><a href="intro.html#cb21-16" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(valor),</span>
<span id="cb21-17"><a href="intro.html#cb21-17" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(valor),</span>
<span id="cb21-18"><a href="intro.html#cb21-18" tabindex="-1"></a>            <span class="at">asimetria =</span> <span class="fu">skewness</span>(valor),</span>
<span id="cb21-19"><a href="intro.html#cb21-19" tabindex="-1"></a>            <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor))</span></code></pre></div>
<pre><code>## # A tibble: 8 × 12
##   variable      n   media     sd mediana    RIC      Q1      Q3   minimo  maximo
##   &lt;chr&gt;     &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 househol… 20640  500.   3.82e2  409    3.25e2  280     605       1      6082  
## 2 housing_… 20640   28.6  1.26e1   29    1.9 e1   18      37       1        52  
## 3 latitude  20640   35.6  2.14e0   34.3  3.78e0   33.9    37.7    32.5      42.0
## 4 longitude 20640 -120.   2.00e0 -118.   3.79e0 -122.   -118.   -124.     -114. 
## 5 median_i… 20640    3.87 1.90e0    3.53 2.18e0    2.56    4.74    0.500    15.0
## 6 populati… 20640 1425.   1.13e3 1166    9.38e2  787    1725       3     35682  
## 7 total_be… 20640  538.   4.19e2  438    3.46e2  297     643.      1      6445  
## 8 total_ro… 20640 2636.   2.18e3 2127    1.70e3 1448.   3148       2     39320  
## # ℹ 2 more variables: asimetria &lt;dbl&gt;, curtosis &lt;dbl&gt;</code></pre>
<div id="ejercicio-1.-gráficas-e-interpretación-de-las-variables-características" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Ejercicio 1. Gráficas e interpretación de las variables características<a href="intro.html#ejercicio-1.-gr%C3%A1ficas-e-interpretaci%C3%B3n-de-las-variables-caracter%C3%ADsticas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="ejercicio">
<p><strong>Enunciado.</strong> Realizar las gráficas de las otras variables, además la interpretación de la tabla y el gráfico quedan como ejercicio.</p>
<p><span class="fuente">Sección 3.4.4 del libro del profesor</span></p>
</div>
<p><strong>Solución.</strong> Interpretación de la tabla. Las ocho variables se dejan separar en tres grupos según lo
que dicen la asimetría y la curtosis.</p>
<p>El primero es el de las variables de conteo: <code>total_rooms</code>, <code>total_bedrooms</code>,
<code>population</code> y <code>households</code>. Todas tienen media muy por encima de la mediana, asimetría
entre 3,4 y 4,9 y curtosis entre 25 y 76. Son distribuciones muy sesgadas a la derecha y
con colas pesadísimas. <code>population</code> es el caso extremo: la mediana es 1.166 habitantes
pero el máximo llega a 35.682, y la curtosis de 76,5 dice que ese máximo no es un caso
aislado sino que hay toda una cola de barrios enormes. Esto tiene sentido porque cada fila
es un bloque censal y los bloques no tienen el mismo tamaño.</p>
<p>El segundo es <code>median_income</code> y <code>housing_median_age</code>, que son variables ya resumidas por
barrio. El ingreso tiene asimetría 1,65 y curtosis 7,95, o sea sesgo a la derecha pero
mucho más suave que los conteos; además está truncado en 15, igual que el precio.
<code>housing_median_age</code> es la más simétrica de todas, con asimetría 0,06 y curtosis 2,2, y
tiene un tope artificial en 52 años.</p>
<p>El tercero es el par de coordenadas, <code>latitude</code> y <code>longitude</code>. Aquí la asimetría y la
curtosis no significan nada sustantivo porque no son magnitudes, son posiciones en el
mapa. La curtosis por debajo de 3 en ambas refleja que California es alargada y que los
barrios están repartidos en dos zonas densas, no que haya algo raro en los datos.</p>
<p>Vamos a ver las cajas de todas las variables características. Como están en escalas muy
distintas, no sirve ponerlas en un mismo eje, así que van con <code>facet_wrap</code> y escala libre.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="intro.html#cb23-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="intro.html#cb23-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>median_house_value, <span class="sc">-</span>latitude, <span class="sc">-</span>longitude) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="intro.html#cb23-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb23-4"><a href="intro.html#cb23-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb23-5"><a href="intro.html#cb23-5" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="intro.html#cb23-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> valor)) <span class="sc">+</span></span>
<span id="cb23-7"><a href="intro.html#cb23-7" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb23-8"><a href="intro.html#cb23-8" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="intro.html#cb23-9" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb23-10"><a href="intro.html#cb23-10" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="intro.html#cb23-11" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="intro.html#cb23-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="intro.html#cb23-13" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/cajascaract-1.png" width="672" /></p>
<p>Y los histogramas de las mismas variables:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="intro.html#cb24-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="intro.html#cb24-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>median_house_value, <span class="sc">-</span>latitude, <span class="sc">-</span>longitude) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="intro.html#cb24-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb24-4"><a href="intro.html#cb24-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb24-5"><a href="intro.html#cb24-5" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="intro.html#cb24-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> valor)) <span class="sc">+</span></span>
<span id="cb24-7"><a href="intro.html#cb24-7" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="intro.html#cb24-8" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb24-9"><a href="intro.html#cb24-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-10"><a href="intro.html#cb24-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/histcaract-1.png" width="672" /></p>
<p>Interpretación de los gráficos. Los cuatro conteos muestran la misma figura: caja
aplastada contra el eje y una nube larga de puntos rojos hacia arriba. Eso es exactamente
lo que anunciaban la asimetría y la curtosis de la tabla. En <code>median_income</code> la caja ya se
ve más centrada, pero se alcanza a notar la barra del tope en 15. <code>housing_median_age</code> es
la única cuya caja queda más o menos en la mitad del rango y casi sin puntos fuera, con la
barra alta del final que son las casas topeadas en 52 años.</p>
<p>Los tres boxplot que trae el profesor en su libro son un caso particular de esto, y se
arman con <code>patchwork</code>:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="intro.html#cb25-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="intro.html#cb25-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="intro.html#cb25-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb25-4"><a href="intro.html#cb25-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="intro.html#cb25-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb25-6"><a href="intro.html#cb25-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="intro.html#cb25-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p1</span>
<span id="cb25-8"><a href="intro.html#cb25-8" tabindex="-1"></a></span>
<span id="cb25-9"><a href="intro.html#cb25-9" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a href="intro.html#cb25-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> total_rooms)) <span class="sc">+</span></span>
<span id="cb25-11"><a href="intro.html#cb25-11" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb25-12"><a href="intro.html#cb25-12" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="intro.html#cb25-13" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb25-14"><a href="intro.html#cb25-14" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a href="intro.html#cb25-15" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p2</span>
<span id="cb25-16"><a href="intro.html#cb25-16" tabindex="-1"></a></span>
<span id="cb25-17"><a href="intro.html#cb25-17" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb25-18"><a href="intro.html#cb25-18" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> total_bedrooms)) <span class="sc">+</span></span>
<span id="cb25-19"><a href="intro.html#cb25-19" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb25-20"><a href="intro.html#cb25-20" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-21"><a href="intro.html#cb25-21" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb25-22"><a href="intro.html#cb25-22" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-23"><a href="intro.html#cb25-23" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p3</span>
<span id="cb25-24"><a href="intro.html#cb25-24" tabindex="-1"></a></span>
<span id="cb25-25"><a href="intro.html#cb25-25" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/trescajas-1.png" width="672" /></p>
<p>Ahora la única variable categórica del conjunto.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="intro.html#cb26-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="intro.html#cb26-2" tabindex="-1"></a>  <span class="fu">count</span>(ocean_proximity, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="intro.html#cb26-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb26-4"><a href="intro.html#cb26-4" tabindex="-1"></a>         <span class="at">Variable   =</span> <span class="st">&quot;Ocean_proximity&quot;</span>,</span>
<span id="cb26-5"><a href="intro.html#cb26-5" tabindex="-1"></a>         <span class="at">Categoria  =</span> <span class="fu">as.character</span>(ocean_proximity)) <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="intro.html#cb26-6" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, n, Porcentaje) <span class="ot">-&gt;</span> tabla_ocean</span>
<span id="cb26-7"><a href="intro.html#cb26-7" tabindex="-1"></a></span>
<span id="cb26-8"><a href="intro.html#cb26-8" tabindex="-1"></a>tabla_ocean</span></code></pre></div>
<pre><code>##          Variable  Categoria    n Porcentaje
## 1 Ocean_proximity  &lt;1H OCEAN 9136      44.26
## 2 Ocean_proximity     INLAND 6551      31.74
## 3 Ocean_proximity     ISLAND    5       0.02
## 4 Ocean_proximity   NEAR BAY 2290      11.09
## 5 Ocean_proximity NEAR OCEAN 2658      12.88</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="intro.html#cb28-1" tabindex="-1"></a>tabla_ocean_b <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="intro.html#cb28-2" tabindex="-1"></a>  <span class="fu">count</span>(ocean_proximity, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="intro.html#cb28-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb28-4"><a href="intro.html#cb28-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb28-5"><a href="intro.html#cb28-5" tabindex="-1"></a></span>
<span id="cb28-6"><a href="intro.html#cb28-6" tabindex="-1"></a>tabla_ocean_b <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="intro.html#cb28-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ocean_proximity, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="intro.html#cb28-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="intro.html#cb28-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">4.5</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="intro.html#cb28-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb28-11"><a href="intro.html#cb28-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución de la variable ocean proximity&quot;</span>,</span>
<span id="cb28-12"><a href="intro.html#cb28-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;ocean_proximity&quot;</span>, <span class="at">y =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="intro.html#cb28-13" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/barraocean-1.png" width="672" /></p>
<p>Casi la mitad de los barrios (44,26%) están a menos de una hora del océano y un tercio
(31,74%) son de tierra adentro. La categoría <code>ISLAND</code> tiene apenas 5 registros, el 0,02%,
así que cualquier promedio que se calcule ahí no es confiable y hay que decirlo cuando
aparezca en las comparaciones.</p>
</div>
</div>
<div id="analisis-exploratorio-bivariado" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Analisis exploratorio bivariado<a href="intro.html#analisis-exploratorio-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="intro.html#cb29-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="intro.html#cb29-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> median_income, <span class="at">y =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="intro.html#cb29-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&quot;#1E90FF&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="intro.html#cb29-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Valor medio&quot;</span>,</span>
<span id="cb29-5"><a href="intro.html#cb29-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Ingreso medio&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="intro.html#cb29-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb29-7"><a href="intro.html#cb29-7" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Dispersion entre ingreso medio y el valor medio de la vivienda&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/valorvsingreso-1.png" width="672" /></p>
<p>Se ve una relación positiva clara: a mayor ingreso medio del barrio, mayor valor de la
vivienda. También se ve la línea horizontal de puntos en 500.001, que es otra vez el tope
artificial, y unas líneas más tenues en 450.000 y 350.000.</p>
<div id="ejercicio-2.-diagramas-de-dispersión-con-las-demás-variables" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Ejercicio 2. Diagramas de dispersión con las demás variables<a href="intro.html#ejercicio-2.-diagramas-de-dispersi%C3%B3n-con-las-dem%C3%A1s-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="ejercicio">
<p><strong>Enunciado.</strong> Realiza los diagramas de dispersión de la variable <code>median_house_value</code> con respecto a las variables independientes que hacen falta.</p>
<p><span class="fuente">Sección 3.4.5 del libro del profesor</span></p>
</div>
<p><strong>Solución.</strong></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="intro.html#cb30-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="intro.html#cb30-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="intro.html#cb30-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>median_house_value,</span>
<span id="cb30-4"><a href="intro.html#cb30-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb30-5"><a href="intro.html#cb30-5" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="intro.html#cb30-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> valor, <span class="at">y =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb30-7"><a href="intro.html#cb30-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="st">&quot;#1E90FF&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="intro.html#cb30-8" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;#47078c&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="intro.html#cb30-9" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&quot;free_x&quot;</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="intro.html#cb30-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valor medio de la casa (USD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-11"><a href="intro.html#cb30-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown-demo_files/figure-html/dispersiones-1.png" width="672" /></p>
<p>Y el coeficiente de correlación de cada una con el precio, para ponerle número a lo que
se ve:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="intro.html#cb32-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="intro.html#cb32-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="intro.html#cb32-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="sc">-</span>median_house_value,</span>
<span id="cb32-4"><a href="intro.html#cb32-4" tabindex="-1"></a>                   <span class="sc">~</span> <span class="fu">cor</span>(.x, median_house_value))) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="intro.html#cb32-5" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;correlacion&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="intro.html#cb32-6" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(correlacion)))</span></code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   variable           correlacion
##   &lt;chr&gt;                    &lt;dbl&gt;
## 1 median_income           0.688 
## 2 latitude               -0.144 
## 3 total_rooms             0.134 
## 4 housing_median_age      0.106 
## 5 households              0.0658
## 6 total_bedrooms          0.0495
## 7 longitude              -0.0460
## 8 population             -0.0246</code></pre>
<p><code>median_income</code> es la única con una relación fuerte, r = 0,688. Las demás quedan por
debajo de 0,15 en valor absoluto, o sea que por sí solas casi no explican el precio. Los
cuatro conteos forman nubes pegadas al eje izquierdo porque están muy sesgados, y ahí la
correlación de Pearson no es una buena medida de la relación. <code>latitude</code> da −0,144 y esa
correlación tampoco hay que leerla como causa: lo que dice es que el norte y el sur de
California tienen precios distintos, no que la latitud haga subir el precio.</p>
<p>Ahora comparemos el valor medio de la vivienda segun la aproximidad al oceano</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="intro.html#cb34-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="intro.html#cb34-2" tabindex="-1"></a>  <span class="fu">group_by</span>(ocean_proximity) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="intro.html#cb34-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(median_house_value),</span>
<span id="cb34-4"><a href="intro.html#cb34-4" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(median_house_value),</span>
<span id="cb34-5"><a href="intro.html#cb34-5" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(median_house_value),</span>
<span id="cb34-6"><a href="intro.html#cb34-6" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(median_house_value),</span>
<span id="cb34-7"><a href="intro.html#cb34-7" tabindex="-1"></a>            <span class="at">RIC =</span> <span class="fu">IQR</span>(median_house_value),</span>
<span id="cb34-8"><a href="intro.html#cb34-8" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(median_house_value, <span class="fl">0.25</span>),</span>
<span id="cb34-9"><a href="intro.html#cb34-9" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(median_house_value, <span class="fl">0.75</span>),</span>
<span id="cb34-10"><a href="intro.html#cb34-10" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(median_house_value),</span>
<span id="cb34-11"><a href="intro.html#cb34-11" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(median_house_value),</span>
<span id="cb34-12"><a href="intro.html#cb34-12" tabindex="-1"></a>            <span class="at">asimetria =</span> <span class="fu">skewness</span>(median_house_value),</span>
<span id="cb34-13"><a href="intro.html#cb34-13" tabindex="-1"></a>            <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(median_house_value))</span></code></pre></div>
<pre><code>## # A tibble: 5 × 12
##   ocean_proximity     n  media     sd mediana    RIC     Q1     Q3 minimo maximo
##   &lt;fct&gt;           &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 &lt;1H OCEAN        9136 2.40e5 1.06e5  214850 125000 164100 289100  17500 500001
## 2 INLAND           6551 1.25e5 7.00e4  108500  71450  77500 148950  14999 500001
## 3 ISLAND              5 3.80e5 8.06e4  414700 150000 300000 450000 287500 450000
## 4 NEAR BAY         2290 2.59e5 1.23e5  233800 183200 162500 345700  22500 500001
## 5 NEAR OCEAN       2658 2.49e5 1.22e5  229450 172750 150000 322750  22500 500001
## # ℹ 2 more variables: asimetria &lt;dbl&gt;, curtosis &lt;dbl&gt;</code></pre>
<p>Veamos un grafico de caja y bigotes</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="intro.html#cb36-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="intro.html#cb36-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ocean_proximity, <span class="at">y =</span> median_house_value)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="intro.html#cb36-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#47078c&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb36-4"><a href="intro.html#cb36-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="intro.html#cb36-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb36-6"><a href="intro.html#cb36-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#b02ca5&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="intro.html#cb36-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proximidad al oceano&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valor medio de la casa (USD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-8"><a href="intro.html#cb36-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/bibocplot-1.png" width="672" /></p>
<p><code>INLAND</code> es el grupo claramente más barato, con mediana de 108.500 frente a 214.850 de
<code>&lt;1H OCEAN</code> y 233.800 de <code>NEAR BAY</code>. Los tres grupos costeros se parecen bastante entre
sí. <code>ISLAND</code> aparece con la media más alta de todas, 380.440, pero son 5 barrios, así que
esa caja no se puede comparar con las otras.</p>
</div>
<div id="ejercicio-3.-errores-del-gráfico-de-ggpairs" class="section level3 hasAnchor" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Ejercicio 3. Errores del gráfico de <code>ggpairs</code><a href="intro.html#ejercicio-3.-errores-del-gr%C3%A1fico-de-ggpairs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="ejercicio">
<p><strong>Enunciado.</strong> Menciona los errores que puedes encontrar en el gráfico.</p>
<p><span class="fuente">Sección 3.4.5 del libro del profesor</span></p>
</div>
<p><strong>Solución.</strong> El gráfico en cuestión es este:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="intro.html#cb37-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="intro.html#cb37-2" tabindex="-1"></a>  <span class="fu">select</span>(median_house_value, median_income, housing_median_age,</span>
<span id="cb37-3"><a href="intro.html#cb37-3" tabindex="-1"></a>         total_rooms, population) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="intro.html#cb37-4" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/ggpairs-1.png" width="672" /></p>
<p>El primero es de legibilidad. Si se le pasa el <code>df</code> completo, <code>ggpairs()</code> arma una malla
de 10×10 con 20.640 puntos en cada panel; los ejes quedan ilegibles y el gráfico tarda
muchísimo en dibujarse. Por eso arriba se seleccionaron solo cinco variables.</p>
<p>El segundo es que mete <code>longitude</code> y <code>latitude</code> como si fueran variables cuantitativas
cualquiera. Calcula su media, su densidad y su correlación con el precio, y ninguna de
esas tres cosas significa algo: la media de una longitud es un punto en el mar y la
correlación entre latitud y precio no describe una relación lineal sino la geografía de
California. Esas dos variables se deberían ver en un mapa, no en un panel de dispersión.</p>
<p>El tercero es que las correlaciones que reporta son de Pearson, que supone relación lineal
y es muy sensible a los valores extremos. Con variables tan sesgadas como <code>population</code> o
<code>total_rooms</code> ese número subestima la asociación real. Para ese caso serviría más Spearman.</p>
<p>El cuarto es que el truncamiento de <code>median_house_value</code> en 500.001 contamina toda la fila
y toda la columna del target: la densidad muestra un pico falso al final y las nubes de
puntos muestran una línea horizontal que no es un patrón del mercado.</p>
<p>Y el quinto es que <code>ggpairs()</code> ignora <code>ocean_proximity</code> si no se incluye. Como ya vimos que
ese factor separa fuerte los precios, mirar solo las relaciones numéricas deja por fuera la
variable que más ordena el conjunto.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-paramétrica-y-no-paramétrica.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/josevang0811/Analisis_exploratorio/edit/main/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
